//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvAgen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int number { get; set; }
        public Nullable<int> customerId { get; set; }
        public string advertisingName { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> statusId { get; set; }
    
        public virtual advertising advertising { get; set; }
        public virtual customer customer { get; set; }
        public virtual status status { get; set; }
    }
}
